server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka  

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: schoolModule
        uri: lb://SCHOOL-SERVICE
        predicates:
        - Path=/school/**
      - id: studentModule
        uri: lb://STUDENT-SERVICE
        predicates:
        - Path=/student/**