#server:
#  port: ${PORT:8761}

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0

server:
  port: 9001    
    
spring:
  application:
    name: eureka-server-clustered   
    
eureka:
  datacenter: Main
  environment: prod
  instance:
    hostname: localhost  
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://localhost:9002/eureka